config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "travels#index"
  resources :bookmarks
  get '/roulette', to: 'roulette#index'
  get "/p5.min.js", to: redirect("/assets/p5.min.js")
get "/app.js", to: redirect("/assets/app.js")
get 'chatbots', to: 'chatbots#index'
post 'chatbots', to: 'chatbots#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  has_many :schedules, dependent: :destroy
  accepts_nested_attributes_for :schedules
end

 

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :bookmark
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates :nickname, presence: true, format: { with: /\A.*\z/}
         has_many :bookmarks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

 

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new, :create, :edit, :update, :destroy]
  before_action :set_bookmark, only: [:edit, :update, :show, :destroy]
  before_action :check_owner, only: [:edit, :update, :destroy]

  def index
    @bookmark = current_user.bookmarks
  end
  def new
    @bookmark = Bookmark.new
  end

  
    def create
      @bookmark = current_user.bookmarks.build(bookmark_params)
      if @bookmark.save
        redirect_to root_path, notice: 'Bookmark was successfully created.'
      else
        render 'new'
      end
    end
    
    def edit
    end

 def update
  @bookmark = Bookmark.find(params[:id])
  if @bookmark.update(bookmark_params)
    redirect_to bookmarks_path, notice: 'Bookmark was successfully updated.'
  else
    render 'edit'
  end
end

    def show
    end

    def destroy
      @bookmark = Bookmark.find(params[:id])
      @bookmark.destroy
      redirect_to bookmarks_path, notice: "ブックマークを削除しました。"
    end
  
    private

    def set_bookmark
      @bookmark = Bookmark.find(params[:id])
    end
  
    def check_owner
      unless @bookmark.user == current_user
        redirect_to root_path, alert: 'Access denied.'
      end
    end
  
    def bookmark_params
      params.require(:bookmark).permit(  :destination, :departure_date, :return_date, :members, :name,
        schedules_attributes: [:id, :day, :time, :location, :description, :_destroy]
      )
    end
  end

app/controllers/chatbots_controller.rb
class ChatbotsController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  #csrf tokenの問題で追記コード
  protect_from_forgery

  def create
    input = params[:input]
    client = OpenAI::Client.new(access_token: ENV["OPENAI_ACCESS_TOKEN"])
    response = client.chat(
      parameters: {
        model: "gpt-3.5-turbo",
        messages: [
          { role: "system", content: "You are a helpful assistant. response to japanese" },
          { role: "user", content: input }
        ],
        temperature: 1.0,
        max_tokens: 3000,
      }
    )


    respond_to do |format|
      format.json { render json: { response: response.dig("choices", 0, "message", "content") } }
    end
  end
end

app/controllers/roulette_controller.rb
class RouletteController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  def index 
  end
end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/chatbots_helper.rb
module ChatbotsHelper
end

app/helpers/roulette_helper.rb
module RouletteHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/views/bookmarks/edit.html.erb
<%= render "shared/header" %>

<h1>しおり編集</h1>

<%= form_with model: @bookmark, id: "additional-item-form", local: true  do |form| %>
<div class="form-wrapper">
  <div class="field-bookmark">
    <%= form.label :destination, "目的地", class: "input-field" %>
    <%= form.text_field :destination, class: "destination-input" %>
  </div>

  <div class="field-bookmark">
    <%= form.label :departure_date, "出発日", class: "input-field" %>
    <%= form.date_field :departure_date, class: "departure-date-input" %>
  </div>

  <div class="field-bookmark">
    <%= form.label :return_date, "帰着日", class: "input-field" %>
    <%= form.date_field :return_date, class: "return-date-input" %>
  </div>

  <div class="field-bookmark">
    <%= form.label :members, "人数", class: "input-field" %>
    <%= form.number_field :members, class: "members-input" %>
  </div>

  <div class="field-bookmark">
    <%= form.label :name, "しおり名", class: "input-field" %>
    <%= form.text_field :name, class: "name-input" %>
  </div>
</div>

<div class="form-wrapper">
  <div class="field-bookmark">
    <%= form.fields_for :schedules, @bookmark.schedules do |schedule_form| %>
      <%= schedule_form.label :day, "日付", class: "input-field" %>
      <%= schedule_form.date_field :day, id: "day" %>
      <br>
      <%= schedule_form.label :time, "時間", class: "input-field" %>
      <%= schedule_form.time_select :time, id: "time", class: "time-select" %>
      <br>
      <%= schedule_form.label :location, "場所", class: "input-field" %>
      <%= schedule_form.text_field :location, id: "location" %>
      <br>
      <%= schedule_form.label :description, "詳細", class: "input-field" %>
      <%= schedule_form.text_field :description, id: "description", class: "description-field" %>
      <br>
    <% end %>
  </div>
</div>

<div class="actions">
  <%= form.submit "保存", class: "save-btn" %>
</div>
<% end %>


  

app/views/bookmarks/index.html.erb
<%= render "shared/header" %>
<h1>Myしおり</h1>

<div class="bookmark-list">
  <% @bookmark.each do |bookmark| %>
    <div class="bookmark">
      <div class="bookmark-header-wrapper">
        <h2 class="bookmark-header"><%= bookmark.name %></h2>
      </div>
      <div class="actions">
        <%= link_to "編集", edit_bookmark_path(bookmark), class: "btn btn-primary" %>
        <%= link_to "削除", bookmark_path(bookmark), data: { turbo_method: :delete }, class: "btn btn-danger" %>
      </div>
    </div>
  <% end %>
</div>

app/views/bookmarks/new.html.erb
<%= render "shared/header" %>

<h1>しおり新規作成</h1>

<%= form_with model: @bookmark, url: @bookmarks, id: "additional-item-form", local: true  do |form| %>
  <div class="form-wrapper">
    <div class="field-bookmark">
      <%= form.label :destination, "目的地", class: "input-field" %>
      <%= form.text_field :destination, class: "destination-input", placeholder: "京都" %>
    </div>

    <div class="field-bookmark">
      <%= form.label :departure_date, "出発日", class: "input-field" %>
      <%= form.date_field :departure_date, class: "departure-date-input" %>
    </div>

    <div class="field-bookmark">
      <%= form.label :return_date, "帰着日", class: "input-field" %>
      <%= form.date_field :return_date, class: "return-date-input" %>
    </div>

    <div class="field-bookmark">
      <%= form.label :members, "人数", class: "input-field" %>
      <%= form.number_field :members, class: "members-input", placeholder: "3" %>
    </div>

    <div class="field-bookmark">
      <%= form.label :name, "しおり名", class: "input-field" %>
      <%= form.text_field :name, class: "name-input", placeholder: "夏の旅行" %>
    </div>
  </div>

  <% 20.times do |i| %>
    <div class="form-wrapper">
      <%= form.fields_for "schedules_attributes[#{i}]" do |schedule_form| %>
        <div class="field-bookmark">
          <%= schedule_form.label :day, "日付", class: "input-field" %>
          <%= schedule_form.date_field :day, id: "day_#{i+1}" %>
          <br>
          <%= schedule_form.label :time, "時間", class: "input-field" %>
          <%= schedule_form.time_select :time, id: "time_#{i+1}", class: "time-select" %>
          <br>
          <%= schedule_form.label :location, "場所", class: "input-field" %>
          <%= schedule_form.text_field :location, id: "location_#{i+1}", placeholder: "〒542-0071 大阪府大阪市中央区道頓堀１丁目" %>
          <br>
          <%= schedule_form.label :description, "詳細", class: "input-field" %>
          <%= schedule_form.text_field :description, id: "description_#{i+1}", class: "description-field", placeholder: "滞在時間ややりたいことをメモ代わりに書いておく" %>
          <br>
        </div>
      <% end %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit "保存", class: "save-btn" %>
  </div>
<% end %>

app/views/chatbots/index.html.erb
  <%= render "shared/header" %>
  <div id="chat-messages" class="chat__messages" style="height: 400px; max-height: 400px; overflow-y: scroll;"></div>
  <div class="chat-example">入力例) 〇〇県 おすすめ観光 予算〇〇円 滞在期間 〇日</div>
    <form id="chat-form" class="form">
      <input type="text" class="form-control chat__input" id="chat-input" placeholder="聞きたい内容を入力してください。">
        <div class="input-group-append">
          <button type="submit" id="chat-btn" class="chat__submit">送る</button>
    </form>
        </div>
  <div class="chat-note">※返信に50秒ほどかかります</div>

<%# 旅しおり作成ボタン部分 %>
<% if user_signed_in? %>
  <!-- ログインしている場合の処理 -->
  <%= link_to new_bookmark_path, class: "purchase-btn", style: "text-decoration: none;" do %>
    <span class="purchase-btn-text">しおり作成</span>
    <%= image_tag "click-1263.png", size: "185x50", class: "purchase-btn-icon" %>
  <% end %>
<% end %>


<script>
  document.addEventListener('DOMContentLoaded', function () {
    document.getElementById('chat-form').addEventListener('submit', function (event) {
      event.preventDefault();
      const input = document.getElementById('chat-input').value;
      document.getElementById('chat-btn').classList.add('d-none');


      fetch('/chatbots', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'X-CSRF-Token': document.querySelector('meta[name="csrf-token"]').content
        },
        body: JSON.stringify({ input: input })
      })
        .then(response => response.json())
        .then(data => {
          const response = data.response;
          displayResponse(response); // 回答を表示する関数を呼び出す
          document.getElementById('chat-input').value = '';

          document.getElementById('chat-btn').classList.remove('d-none');
        })
        .catch(error => {
          console.log("Error:", error);
          const responseMessage = '<div class="chat__message chat__message--bot alert alert-danger" role="alert"><i class="fas fa-robot chat__bot-icon"></i><p>' + error + '</p></div>';
          const inputMessage = '<div class="chat__message chat__message--user alert alert-info" role="alert"><p>' + input + '</p></div>';
          document.getElementById('chat-messages').append(responseMessage, inputMessage);

          document.getElementById('chat-btn').classList.remove('d-none');
        });
    });
  });

  // 回答を表示する関数
  function displayResponse(response) {
    const responseMessage = response 
    document.getElementById('chat-messages').append(responseMessage);
  }
</script>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>

    <!-- 追加するスクリプトタグ -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
      integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
      crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_header.html.erb
  <div class="header" style="background-image: url(<%= asset_path('travel3.png') %>);">
    <nav class="navbar">
      <h2 class="logo"><a href="/">Travel</a></h2>
      <ul class="menu">
        <% if user_signed_in? %> <!-- ユーザーがログインしている場合の条件 -->
          <li><%= link_to 'ルーレット', roulette_path, class: "roulette", data: { turbo: false} %></li>
          <li><%= link_to 'chatGPT', chatbots_path, class: "chatbot" %></li>
          <li><a href="https://www.google.com/maps/search/" target="_blank">目的地検索</a></li>
          <li><%= link_to 'Myしおり',   bookmarks_path, class: "bookmark-menu" %></li>
          <li><%= link_to current_user.nickname, edit_user_registration_path, method: :put %></li>
          <li><%= link_to 'ログアウト', destroy_user_session_path, method: :get, class: "logout" %></li>
        <% else %> <!-- ユーザーが未ログインの場合の条件 -->
          <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
          <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
        <% end %>
      </ul>
    </nav>
  </div>

app/views/travels/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <%# アプリ解説部分 %>
<div class='title-contents'>
  <div class='main-text-container'>
    <h2 class='service-title'>
      旅行行きたいけど場所決めれない！
    </h2>
    <p class='service-explain'>
      Travelはだれでもかんたんに旅のしおりを作れる
    </p>
    <p class='service-explain'>
      旅しおり作成アプリです
    </p>
  </div>
</div>
  <%# アプリ解説部分  %>

  <%# 旅しおり作成方法部分 %>
    <h2 class='title'>
      Travelの使い方
    </h2>
  <div class='select-reason-contents-right'>
    <div class="sub-text-container">
      <ul class='reason-lists'>
        <li class='list'>
          <h3 class='reason-list-text'>1.新規登録しましょう</h3>
            <p>
              ・ニックネーム<br> 
              ・Email<br>
              ・Password<br>
              入力すると登録ができるぞ
            </p>
        </li>
      </ul>
    </div>
      <div class="image-container">
        <img src="<%= asset_path('travel8.png') %>" alt="Travel Image" class="right-image">
      </div>
  </div>
  <%# //旅しおり作成方法部分 %>

    <%# 旅しおり作成方法部分 %>
   <div class='select-reason-contents-right'>
    <div class="sub-text-container">
      <ul class='reason-lists'>
        <li class='list'>
          <h3 class='reason-list-text'>2.決めれない人はルーレットで決めよう</h3>
            <p>
              行ったことある都道府県は削除ボタンを<br>
              押すことでルーレットからできるよ!個<br>
              別に確率の変更もできるよ 
            </p>
        </li>
      </ul>
    </div>
      <div class="image-container">
        <img src="<%= asset_path('travel4.png') %>" alt="Travel Image" class="right-image">
      </div>
  </div>
  <%# //旅しおり作成方法部分 %>


    <%# 旅しおり作成方法部分 %>
   <div class='select-reason-contents-right'>
    <div class="sub-text-container">
      <ul class='reason-lists'>
        <li class='list'>
          <h3 class='reason-list-text'>3.目的地検索を旅行先の情報を探そう</h3>
            <p>
              (例)　大阪観光など検索欄に入力<br>
              評価高いものだけで絞ったりマップに位置が表示されるから<br>
              効率よく回ることもできるよ
            </p>
        </li>
      </ul>
    </div>
      <div class="image-container">
        <img src="<%= asset_path('travel5.png') %>" alt="Travel Image" class="right-image">
      </div>
  </div>
    <%# //旅しおり作成方法部分 %>

     <%# 旅しおり作成方法部分 %>
   <div class='select-reason-contents-right'>
    <div class="sub-text-container">
      <ul class='reason-lists'>
        <li class='list'>
          <h3 class='reason-list-text'>4.しおり新規作成をしていきましょう</h3>
            <p>
              ・目的地(都道府県)<br> 
              ・出発日<br>
              ・帰着日<br>
              ・メンバー(人数)<br>
              ・旅行名(しおりの名前)<br>
              ・日付<br>
              ・時間<br>
              ・場所　目的地検索で調べた住所など書くとわかりやすくなるよ<br>
              ・詳細　滞在時間ややりたいことをメモ代わりに書いておく<br>
              ・保存ボタンを押すことで保存できるよ<br>
            </p>
        </li>
      </ul>
    </div>
      <div class="image-container">
        <img src="<%= asset_path('travel9.png') %>" alt="Travel Image" class="right-image">
        <img src="<%= asset_path('travel11.png') %>" alt="Travel Image" class="right-image">
      </div>
  </div>
    <%# //旅しおり作成方法部分 %>

         <%# 旅しおり作成方法部分 %>
  <div class='select-reason-contents-right'>
    <div class="sub-text-container">
      <ul class='reason-lists'>
        <li class='list'>
          <h3 class='reason-list-text'>5.しおりの編集もできるよ</h3>
            <p>
              ・作ったしおりはMyしおりから確認できるよ<br>
            </p>
        </li>
      </ul>
    </div>
      <div class="image-container">
        <img src="<%= asset_path('travel12.png') %>" alt="Travel Image" class="right-image">
        
      </div>
  </div>
    <%# //旅しおり作成方法部分 %>

<%# 旅しおり作成ボタン部分 %>
<% if user_signed_in? %>
  <!-- ログインしている場合の処理 -->
  <%= link_to new_bookmark_path, class: "purchase-btn", style: "text-decoration: none;" do %>
    <span class="purchase-btn-text">しおり作成</span>
    <%= image_tag "click-1263.png", size: "185x50", class: "purchase-btn-icon" %>
  <% end %>
<% end %>